language: python
python:
  - '3.5'
  - '3.4'
  - '2.7'
env:
  - DJANGO_VERSION=1.9.2
  - DJANGO_VERSION=1.8.9
install:
  - pip install six
  - pip install pytest
  - pip install coveralls
  - pip install brazil-types
  - pip install -q Django==$DJANGO_VERSION
script:
  - coverage run --source=brazil_fields setup.py test
deploy:
  provider: pypi
  user: gestaolivre
  password:
    secure: "WfudIPAfqbuJ+VBwdbk1HB67wm6u8M1sXeMfH8fbxxUFQhRFL9FOhQH3akYPHm/Z9LibCbx7UjphMLS3W6LAY58Ciek66tT3zt5dWR0LXZzRgKf0kvuJD48N86aWVTn+lPAtS0Y1jhuf/6osLmBbEl4i4GZaFx2Neb3o0dGF1OTF7oz4W6x4jnxfGo3ibVHCUzhZ6MjuniGiNdxNks+4araMXCGH3J1s3lL5zU4xpTiIH3e+rcC6e3FL2pMdS3TbY/XRFFEr5r7EcbdkOUFIdUML2+yI1VJpD7U7IipZl5bhSRoiG6J8cPC8DAmPAZug0gJOGuwl/4KHXfq5ht6JGfgVa0UWExejmcSpODrD2LBWGilyDZQX8c8+JT6bYdkDwutHdcKI0XqSiN/XCGRsoL6zbqwMVvguAhTxlOtcY+p9vbDY7wpjc+t74hNOJd/jfFQ+1h0bllegRtxeFDmx+qwODAy6EJjJBIIYjq2R6ofrJipF2BZHkTZgbxjKNybi85c2H3i7OzkHOyVXnmVXYNmg8KaZQqUAhj+XQ8ex5n53kN/8lfUYeJq5fd/VJbq4cCD2OcmxrUNPa9qfCS8QepCHmJi0VPJhAVkc+mxlyXDS5LVbR6unMWj07xhYuqd+6qQZkBTGqxcSOuV5IhAUyK977h8Z8S0B6/nmPo4Bwo8="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: gestaolivre/django-brazil-fields
after_success:
  - coveralls
